version: "3"

services:
  nodo1:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - GRPC_PORT=8000
      - GRPC_CLIENT=8001
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
  nodo2:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - GRPC_PORT=8001
      - GRPC_CLIENT=8002
    volumes:
      - .:/usr/src/app
    ports:
      - 8001:8001
  nodo3:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - GRPC_PORT=8002
      - GRPC_CLIENT=8000
    volumes:
      - .:/usr/src/app
    ports:
      - 8002:8002
