version: "3"

services:
  nodo1:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - GRPC_PORT_SERVER=8000
    volumes:
      - .:/usr/nodo
      - ./logs/test1.log:/usr/nodo/logs/debug.log
    ports:
      - 8000:8000
    logging:
      options:
        max-size: "200k"
        max-file: "10"
        labels: "prueba"
  nodo2:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - GRPC_PORT_SERVER=8001
    volumes:
      - .:/usr/nodo
      - ./logs/test2.log:/usr/nodo/logs/debug.log
    ports:
      - 8001:8001
    logging:
      options:
        max-size: "200k"
        max-file: "10"
        labels: "prueba"
  nodo3:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - GRPC_PORT_SERVER=8002
    volumes:
      - .:/usr/nodo
      - ./logs/test3.log:/usr/nodo/logs/debug.log
    ports:
      - 8002:8002
    logging:
      options:
        max-size: "200k"
        max-file: "10"
        labels: "prueba"
    depends_on:
      - nodo1
      - nodo2
networks:
  default:
    # Use a custom driver
    driver: bridge