version: "3"

services:
  nodo1:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - GRPC_PORT=8000
      - GRPC_CLIENT=8001
    volumes:
      - .:/usr/nodo
      - ./logs/test1.log:/usr/nodo/logs/debug.log
    ports:
      - 8000:8000
    logging:
      options:
        max-size: "200k"
        max-file: "10"
        labels: "prueba"
  nodo2:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - GRPC_PORT=8001
      - GRPC_CLIENT=8002
    volumes:
      - .:/usr/nodo
      - ./logs/test2.log:/usr/nodo/logs/debug.log
    ports:
      - 8001:8001
    logging:
      options:
        max-size: "200k"
        max-file: "10"
        labels: "prueba"
  nodo3:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - GRPC_PORT=8002
      - GRPC_CLIENT=8000
    volumes:
      - .:/usr/nodo
      - ./logs/test3.log:/usr/nodo/logs/debug.log
    ports:
      - 8002:8002
    logging:
      options:
        max-size: "200k"
        max-file: "10"
        labels: "prueba"